paramemeterized tasks and modifed defaults
Tinker-Ware/ansible-rails-role pull request #1
Opened 2017-01-13 18:50 UTC by JavierCroisade

Parametrized tasks and modifed defaults

2017-01-13 18:53 UTC, AAlvz requested changes
Fix variables usage

2017-01-13 18:53 UTC, AAlvz commented on tasks/main.yml
> +    chdir: /home/vagrant/ruby-"{{ruby_version}}"/
when using varialbes, the whole line should be between "". like this:
chdir: `"/home/vagrant/ruby-{{ruby_version}}"`

Please fix this for the following lines as well

2017-01-13 18:54 UTC, JavierCroisade commented on tasks/main.yml
> +    chdir: /home/vagrant/ruby-"{{ruby_version}}"/
My deares friend, I will sure do what you ask.

2017-01-13 19:35 UTC, AAlvz commented on tasks/main.yml
> +    dest: "{{home_path}}"
Let's write all variabes with spaces between mustaches. 
`{{ home_path }}`

2017-01-13 19:36 UTC, AAlvz commented on tasks/main.yml
> +    chdir: "/home/vagrant/ruby-{{ruby_version}}/"
Let's avoid the last `/` . we can assume with chdir that we refer to a directory

2017-01-13 19:38 UTC, AAlvz requested changes
Improve code standard and better variable definition

2017-01-13 19:40 UTC, JavierCroisade commented on tasks/main.yml
> +    dest: "{{home_path}}"
Thanks for your observations, old sport , I will see it done inmedeately.

2017-01-13 19:41 UTC, JavierCroisade commented on tasks/main.yml
> +    chdir: "/home/vagrant/ruby-{{ruby_version}}/"
I shall resume the task right away.

2017-01-18 00:32 UTC, AAlvz approved these changes

2017-01-18 00:32 UTC, merged